refactor: release patterns, remove uds bundle (#43)

diff --git a/tasks/setup/main.yaml b/tasks/setup/main.yaml
--- a/tasks/setup/main.yaml
+++ b/tasks/setup/main.yaml
@@ -1,44 +1,44 @@
-includes:
-  - infra: ./infra.yaml
+# includes:
+#   - infra: ./infra.yaml
 
-variables:
-  - name: REGISTRY1_TEST_IMAGE
-    default: "registry1.dso.mil/ironbank/opensource/defenseunicorns/zarf/zarf-agent"
+# variables:
+#   - name: REGISTRY1_TEST_IMAGE
+#     default: "registry1.dso.mil/ironbank/opensource/defenseunicorns/zarf/zarf-agent"
 
-tasks:
-  - name: k3d-istio-bundle
-    actions:
-      - description: "Deploy the UDS Core Istio Only Bundle"
-        cmd: uds deploy oci://ghcr.io/defenseunicorns/packages/uds/bundles/k3d-core-istio-dev:${UDS_K3D_CORE_ISTIO_VERSION}-${UDS_ARCH} --confirm --no-progress
+# tasks:
+#   - name: k3d-istio-bundle
+#     actions:
+#       - description: "Deploy the UDS Core Istio Only Bundle"
+#         cmd: uds deploy oci://ghcr.io/defenseunicorns/packages/uds/bundles/k3d-core-istio-dev:${UDS_K3D_CORE_ISTIO_VERSION}-${UDS_ARCH} --confirm --no-progress
 
-  - name: aws-infra-up
-    description: "Main entrypoint for setting up aws IaC"
-    actions:
-      - task: infra:aws-infra-up
+#   - name: aws-infra-up
+#     description: "Main entrypoint for setting up aws IaC"
+#     actions:
+#       - task: infra:aws-infra-up
 
-  - name: registry-login
-    inputs:
-      registry:
-        description: "Registry"
-      registryUsername:
-        description: "Registry username"
-      registryPassword:
-        description: "Registry password"
-      registryRetryInterval:
-        default: "5"
-        description: "Registry retry interval"
-    actions:
-      - cmd: |
-          echo ${{ .inputs.registryPassword }} | \
-            uds zarf tools registry login \
-            --username ${{ .inputs.registryUsername }} \
-            --password-stdin ${{ .inputs.registry }} \
-            >/dev/null
-        description: "Authenticate to the registry"
-      - cmd: |
-          if [ ${{ .inputs.registry }} = "registry1.dso.mil" ]; then
-            uds zarf tools registry digest "${REGISTRY1_TEST_IMAGE}" >/dev/null || \
-            (sleep ${{ .inputs.registryRetryInterval }}; exit 1)
-          fi
-        description: "Validate registry connection"
-        maxRetries: 10
+#   - name: registry-login
+#     inputs:
+#       registry:
+#         description: "Registry"
+#       registryUsername:
+#         description: "Registry username"
+#       registryPassword:
+#         description: "Registry password"
+#       registryRetryInterval:
+#         default: "5"
+#         description: "Registry retry interval"
+#     actions:
+#       - cmd: |
+#           echo ${{ .inputs.registryPassword }} | \
+#             ./uds zarf tools registry login \
+#             --username ${{ .inputs.registryUsername }} \
+#             --password-stdin ${{ .inputs.registry }} \
+#             >/dev/null
+#         description: "Authenticate to the registry"
+#       - cmd: |
+#           if [ ${{ .inputs.registry }} = "registry1.dso.mil" ]; then
+#             ./uds zarf tools registry digest "${REGISTRY1_TEST_IMAGE}" >/dev/null || \
+#             (sleep ${{ .inputs.registryRetryInterval }}; exit 1)
+#           fi
+#         description: "Validate registry connection"
+#         maxRetries: 10
